{% set name = "simdna" %}
{% set version = "0.4.3.1" %}
{% set sha256 = "01f329ab80fd7d834cbf9eaea88e77c9760f1a7756061feb2fe342b8a2695e7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - matplotlib
    - scipy
    - numpy >=1.9

test:
  imports:
    - simdna

about:
  home: https://github.com/kundajelab/simdna
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license_family: MIT
  summary: 'Simulated datasets of DNA'
  description: |
    Simulated datasets of DNA.
  doc_url: https://kundajelab.github.io/simdna/
  dev_url: https://kundajelab.github.io/simdna/

extra:
  recipe-maintainers:
    - lilleswing
