travis:
  secure:
    BINSTAR_TOKEN: exVCt+PUkKEtazZqxM71d/iKbXXi8/c6bEbqSKbMkU06AUR4y79jB6ITWxG5whBaMIYKS0flMVzEP7KwG+C/ZBg+ujWcEVztWpKswmJQKn2klY+3KhbfSyp+Lx5HS5G44/d1xJ/9feB/sd2GafUhqx58MCzxAYY59LWEp+mL52i/viealEKM3QgbVQYLjPVv+jv/H4B5YnSDVC8zQWS/9cs9TvnI3gwCyTcsGrt/AMQ4q8AfImrowCXgVovUyjx/daFlsFUhfgC4QHIF0m3Y+Ngftwcht/ZzV6Z4VR2muI/1EvRBh/0HLX9FxfzoAGhu7oJnXIwbgRZrfvVYKiE24NGMx4Udj5EFRFAnujNobEAE3ua9Hj4c+Yje6dbxjNYk3Hb3C8P5SIqI9cRCoA74bxFrzPqXeWbPqxkaHspzmlfNJ/jkYfTWRvUcaPU5AwnaMVnB1PMQKZdrv+Ud9Ta3HGDBu/5+YfDLUrvoMK6L9LImFBHhC/zkljl2loD5Jeq1ifu219alW4shdd51Lm3TTKBll1UQwJl8RS5CizGRY0J+uaYbO1jxtODj/i1YC0Kahht5rlAYJzeTLUg8TA3oaMd1/2vLOzQuff2lqFkcqxq9kHGoQLeEbeV3QVcSwoedvCaWQsf+mLL6bHgqejP74LD2nUPAN6PI8ptIX+Fc5pA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
