travis:
  secure:
    BINSTAR_TOKEN: n9InDw0WZMMfvtuKMCnBltFRK8/osaMzV1ei5Bx9NXoUBT2vOr/e6PAuNWkYrqK1fgLmNrvj9P7vBFzfmswjkf7Vv4tXpxN0XYTz1Y4E1Bl8b9vtDKUwF72+5EbW0kFwS15aW28+CxIrPzDcaFFi8ECiAwWnEZ5RtZgy5ZCN1TZFFvKHPKkVnt0NbClhdeOcbFgBf3+gSZaDzrskS29OA6DDtjEbxHia/SE8i1YeirK1O9G6jE2bll+ERK9MZqwBiYXM+Im+zcIYE4TI/h4zwmoDPZa+viSKsHNoLG5cbLzNoVLdGjhrC08LXnpTUqFLfmJNpGrqzv4+vSHRVRV2e6gmBq5t7cWdL/FMU3GSUyDckTdZkGzI0IUgymaO0tNteIfshypw4qBWsexL4z3eL3oXOG1kBSNaU5vw+X3PD/ZsmdsPpSBZLTQw2XRWdKzZjHpfLdnHDRHxVGfPBlFQxFx39o/QgXYjOtlmwzHl70jOzvH1go2lMHypp6JQ2zx12IHb+pmZHtOhlGcODWej6Mx9/7ezJ2bwST6rIOEsbPCX5aTGRL3qnhpJ7YFHqe5G1Q43s9yH35DW2/8pXShSWS7I+Yt3rsogG5F53ciAisFhqROUoHcYxt3yem24bGBmxiNg6YBl7d1ZdjO0GSEMxp5bSMHHASFU5bp1RW0o3yM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
