travis:
  secure:
    BINSTAR_TOKEN: i4QE4TjWx23JnlA8+MSrGHFWYKYMACSus6PGtefjqirb9b89xyoXprFNdmOlbCaGQ7r2GczAYIRQ68j0wQ7LLx/UMfBfh9uUkOCUnczwyQ7WWO9I4aJQbeqzvChYipFKgMU9wqjCnQZ3v26Yx+bULcOp2ETupjfp/4EmEP0WMsBovE9RWn3MNFenNsFKETviZWpGfnNnDj5UrGIJWkR5Dw1UciBC4PhVldMntGGAyrlHpweHGkM0mhXjchVmQauWCHCNmirU8jv5X0jVnYeyx2l/VJtMZ/goZGW6XLaoBGpgmla++W4//R9R9d5bl9mHLbUXWjP99O4N0p08fDKWElY31gWM2h5FERtKMNPChjDLv3Mb/Dj7mEP3hIjEK5DChBAz0ybIsJbyDECKoklyYbBKuAwgl+3UbkZHICS1cwsWJ5Q2Vo1Yy56ldZPdZL5nfWP9bnLt6uHkqcoWEs2MG/6I+8VJOpPzHdSXf8OcwmB8/h5AS1QcNLa9gmc8zRqPJT04kkEVwZUumI0ppWIKfNyQI53uA36y4TcIkdLmbyVmOlrRmLbn6bFPR+nyBk1qD9jCcQkdQn7Z7T6QDudJ1ljRnwRx3emCBK5RFAyev8ysa7GB4EWRWOYYrbBYIn/+jVhEztJl9giBc3H7+P02OkqcG0v0/l6s24erJzXTmvE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
